services:
  minecraft-zoo:
    image: 05jchambers/legendary-bedrock-container:latest
    container_name: minecraft-zoo-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "19132:19132/udp"  # Minecraft Bedrock IPv4
      - "19132:19132/tcp"  # Minecraft Bedrock IPv4 TCP
      - "19133:19133/udp"  # Minecraft Bedrock IPv6
      - "19133:19133/tcp"  # Minecraft Bedrock IPv6 TCP
    volumes:
      - minecraft-zoo-data:/minecraft
      - ./packs:/minecraft/behavior_packs
      - ./packs:/minecraft/resource_packs
    environment:
      - TZ=America/New_York
      - NoPermCheck=Y
      - QuietCurl=Y
    networks:
      - zoo-network

volumes:
  minecraft-zoo-data:
    driver: local

networks:
  zoo-network:
    driver: bridge 